//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTopicStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeTai()
        {
            this.TienDoes = new HashSet<TienDo>();
        }
    
        public string MaDT { get; set; }
        public string TenDT { get; set; }
        public string LoaiDT { get; set; }
        public string NoiDung { get; set; }
        public string MaNhom { get; set; }
        public string MaGV { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Nhom Nhom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDo> TienDoes { get; set; }
        public override string ToString()
        {
            return this.MaDT;
        }
    }
}
