//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTopicStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string MaNhom { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string EmailSV { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual Nhom Nhom { get; set; }
    }
}
